export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  type: 'CLT' | 'PJ' | 'Estágio' | 'Temporário';
  modality: 'Remoto' | 'Híbrido' | 'Presencial';
  level: 'Júnior' | 'Pleno' | 'Sênior';
  salary?: string;
  description: string;
  requirements: string[];
  benefits: string[];
  postedAt: string;
  source: string;
  applicationUrl: string;
  isUrgent?: boolean;
  isFeatured?: boolean;
  isSimplified?: boolean;
}

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Desenvolvedor Frontend React',
    company: 'TechBrasil',
    companyLogo: 'https://ui-avatars.com/api/?name=TB&background=3b82f6&color=fff',
    location: 'São Paulo, SP',
    type: 'CLT',
    modality: 'Remoto',
    level: 'Pleno',
    salary: 'R$ 8.000 - R$ 12.000',
    description: 'Estamos buscando um desenvolvedor Frontend apaixonado por criar interfaces incríveis. Você trabalhará com React, TypeScript e as melhores práticas do mercado.',
    requirements: ['React.js', 'TypeScript', 'Tailwind CSS', 'Git', 'Inglês intermediário'],
    benefits: ['Vale Refeição', 'Plano de Saúde', 'PLR', 'Home Office', 'Gympass'],
    postedAt: '2024-01-15',
    source: 'LinkedIn',
    applicationUrl: '#',
    isFeatured: true,
    isSimplified: true,
  },
  {
    id: '2',
    title: 'Analista de Dados Sênior',
    company: 'DataFlow Analytics',
    companyLogo: 'https://ui-avatars.com/api/?name=DF&background=10b981&color=fff',
    location: 'Rio de Janeiro, RJ',
    type: 'CLT',
    modality: 'Híbrido',
    level: 'Sênior',
    salary: 'R$ 15.000 - R$ 20.000',
    description: 'Procuramos um analista de dados experiente para liderar projetos de BI e criar dashboards estratégicos para tomada de decisão.',
    requirements: ['Python', 'SQL', 'Power BI', 'Machine Learning', 'Estatística'],
    benefits: ['Vale Alimentação', 'Plano de Saúde', 'Bônus anual', 'Flexibilidade de horário'],
    postedAt: '2024-01-14',
    source: 'Glassdoor',
    applicationUrl: '#',
    isUrgent: true,
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'Creative Hub',
    companyLogo: 'https://ui-avatars.com/api/?name=CH&background=8b5cf6&color=fff',
    location: 'Curitiba, PR',
    type: 'PJ',
    modality: 'Remoto',
    level: 'Pleno',
    salary: 'R$ 10.000 - R$ 14.000',
    description: 'Buscamos um designer criativo para revolucionar a experiência do usuário em nossos produtos digitais.',
    requirements: ['Figma', 'Design Systems', 'Prototipagem', 'User Research', 'HTML/CSS básico'],
    benefits: ['Projeto flexível', 'Equipamento fornecido', 'Cursos pagos'],
    postedAt: '2024-01-13',
    source: 'Gupy',
    applicationUrl: '#',
    isSimplified: true,
  },
  {
    id: '4',
    title: 'Estagiário de Marketing Digital',
    company: 'StartupBR',
    companyLogo: 'https://ui-avatars.com/api/?name=SB&background=f59e0b&color=fff',
    location: 'Belo Horizonte, MG',
    type: 'Estágio',
    modality: 'Presencial',
    level: 'Júnior',
    salary: 'R$ 1.500 - R$ 2.000',
    description: 'Oportunidade para estudantes que desejam aprender sobre marketing digital em uma startup em crescimento.',
    requirements: ['Cursando Marketing ou áreas afins', 'Interesse em redes sociais', 'Boa comunicação'],
    benefits: ['Bolsa auxílio', 'Vale transporte', 'Mentoria', 'Possibilidade de efetivação'],
    postedAt: '2024-01-12',
    source: 'Catho',
    applicationUrl: '#',
  },
  {
    id: '5',
    title: 'Engenheiro DevOps',
    company: 'CloudTech Solutions',
    companyLogo: 'https://ui-avatars.com/api/?name=CT&background=06b6d4&color=fff',
    location: 'Porto Alegre, RS',
    type: 'CLT',
    modality: 'Remoto',
    level: 'Sênior',
    salary: 'R$ 18.000 - R$ 25.000',
    description: 'Procuramos um DevOps Engineer para automatizar e otimizar nossa infraestrutura em nuvem.',
    requirements: ['AWS/GCP', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD'],
    benefits: ['Salário competitivo', 'Stock options', 'Trabalho 100% remoto', 'Budget para educação'],
    postedAt: '2024-01-11',
    source: 'LinkedIn',
    applicationUrl: '#',
    isFeatured: true,
    isUrgent: true,
  },
  {
    id: '6',
    title: 'Product Manager',
    company: 'InovaDigital',
    companyLogo: 'https://ui-avatars.com/api/?name=ID&background=ec4899&color=fff',
    location: 'São Paulo, SP',
    type: 'CLT',
    modality: 'Híbrido',
    level: 'Sênior',
    salary: 'R$ 20.000 - R$ 28.000',
    description: 'Lidere o desenvolvimento de produtos digitais inovadores em uma das maiores fintechs do Brasil.',
    requirements: ['Experiência em gestão de produto', 'Metodologias ágeis', 'Análise de métricas', 'Inglês fluente'],
    benefits: ['PLR', 'Ações da empresa', 'Plano de saúde premium', 'Auxílio home office'],
    postedAt: '2024-01-10',
    source: 'Indeed',
    applicationUrl: '#',
    isFeatured: true,
  },
  {
    id: '7',
    title: 'Desenvolvedor Backend Node.js',
    company: 'API Masters',
    companyLogo: 'https://ui-avatars.com/api/?name=AM&background=84cc16&color=fff',
    location: 'Florianópolis, SC',
    type: 'CLT',
    modality: 'Remoto',
    level: 'Pleno',
    salary: 'R$ 9.000 - R$ 13.000',
    description: 'Desenvolva APIs escaláveis e microsserviços para milhões de usuários.',
    requirements: ['Node.js', 'TypeScript', 'PostgreSQL', 'Redis', 'Docker'],
    benefits: ['Vale refeição', 'Plano odontológico', 'Day off no aniversário', 'Cursos Udemy'],
    postedAt: '2024-01-09',
    source: 'Glassdoor',
    applicationUrl: '#',
    isSimplified: true,
  },
  {
    id: '8',
    title: 'Analista de Suporte Técnico',
    company: 'HelpDesk Pro',
    companyLogo: 'https://ui-avatars.com/api/?name=HP&background=64748b&color=fff',
    location: 'Campinas, SP',
    type: 'Temporário',
    modality: 'Presencial',
    level: 'Júnior',
    salary: 'R$ 3.000 - R$ 4.000',
    description: 'Atenda chamados de suporte técnico e ajude nossos clientes a resolver problemas de TI.',
    requirements: ['Conhecimento em Windows/Linux', 'Boa comunicação', 'Trabalho em equipe'],
    benefits: ['Vale transporte', 'Vale alimentação', 'Possibilidade de efetivação'],
    postedAt: '2024-01-08',
    source: 'Catho',
    applicationUrl: '#',
  },
  {
    id: '9',
    title: 'Tech Lead Full Stack',
    company: 'ScaleUp Tech',
    companyLogo: 'https://ui-avatars.com/api/?name=ST&background=0ea5e9&color=fff',
    location: 'Recife, PE',
    type: 'CLT',
    modality: 'Híbrido',
    level: 'Sênior',
    salary: 'R$ 22.000 - R$ 30.000',
    description: 'Lidere um time de desenvolvedores e arquitete soluções de alta performance.',
    requirements: ['Liderança técnica', 'React/Node.js', 'AWS', 'Arquitetura de sistemas', 'Mentoria'],
    benefits: ['Participação nos lucros', 'Horário flexível', 'Plano de carreira estruturado'],
    postedAt: '2024-01-07',
    source: 'LinkedIn',
    applicationUrl: '#',
    isFeatured: true,
    isUrgent: true,
  },
  {
    id: '10',
    title: 'QA Engineer',
    company: 'QualityFirst',
    companyLogo: 'https://ui-avatars.com/api/?name=QF&background=f97316&color=fff',
    location: 'Brasília, DF',
    type: 'PJ',
    modality: 'Remoto',
    level: 'Pleno',
    salary: 'R$ 8.000 - R$ 11.000',
    description: 'Garanta a qualidade dos nossos produtos através de testes automatizados e manuais.',
    requirements: ['Cypress/Selenium', 'Jest', 'API Testing', 'Metodologias ágeis', 'SQL'],
    benefits: ['Flexibilidade total', 'Projetos desafiadores', 'Networking internacional'],
    postedAt: '2024-01-06',
    source: 'Gupy',
    applicationUrl: '#',
    isSimplified: true,
  },
  {
    id: '11',
    title: 'Inspetor de Qualidade',
    company: 'Indústria Metalúrgica',
    companyLogo: 'https://ui-avatars.com/api/?name=IM&background=64748b&color=fff',
    location: 'Gravataí, RS',
    type: 'CLT',
    modality: 'Presencial',
    level: 'Pleno',
    salary: 'R$ 4.500 - R$ 6.000',
    description: 'Buscamos profissional para inspeção de peças em linha de produção automotiva.',
    requirements: ['Metrologia', 'Desenho Técnico', 'Experiência em Indústria'],
    benefits: ['Plano de saúde', 'Alimentação no local', 'Transporte fretado'],
    postedAt: '2024-01-22',
    source: 'InfoJobs',
    applicationUrl: '#',
  },
  {
    id: '12',
    title: 'Desenvolvedor Java/Spring',
    company: 'Bancário Tech',
    companyLogo: 'https://ui-avatars.com/api/?name=BT&background=3b82f6&color=fff',
    location: 'Curitiba, PR',
    type: 'CLT',
    modality: 'Híbrido',
    level: 'Sênior',
    salary: 'R$ 15.000 - R$ 19.000',
    description: 'Atue no desenvolvimento de sistemas bancários escaláveis de alta performance.',
    requirements: ['Java 21', 'Spring Boot', 'Kafka', 'Kubernetes'],
    benefits: ['PLR', 'Previdência Privada', 'Auxílio Educação'],
    postedAt: '2024-01-21',
    source: 'Gupy',
    applicationUrl: '#',
  },
];

export const jobSources = [
  'LinkedIn',
  'Glassdoor',
  'Indeed',
  'Gupy',
  'Catho',
  'InfoJobs',
  'Vagas.com',
  'Trampos.co',
];
